### ISSUE TITLE
[IMPROVEMENT] Upgrade gradle's required version

### ISSUE THREAD

**Issue by henryx** [jopenlibs/vault-java-driver#32]
At the moment, the project is built using Gradle 5.6.4. According to [this issue](https://github.com/gradle/gradle/issues/10807), this version cannot be used with Java greather than 11. This is a problem because it doesn't allow updating the Java version used for project development. therefore it is necessary to carry out the activities necessary to allow Gradle to be updated, in particular by rewriting the deprecated parts in the new versions.  An alternative is change the build system (with Maven or other), but it is preferrable to adopt this way as extrema ration

**Comment by kLeZ** [comment]
Trying to help on this. Just forked.

**Comment by henryx** [comment]
@HomeOfTheWizard Thank you so much for you PR, I've merged it in mainline before check the CI result
