### ISSUE TITLE
5.4.0 not available on Maven.

### ISSUE THREAD

**Issue by brycechesternewman** [jopenlibs/vault-java-driver#36]
Related to https://github.com/jopenlibs/vault-java-driver/pull/34. I am not seeing 5.4.0 on maven. For example https://repo1.maven.org/maven2/io/github/jopenlibs/vault-java-driver/ nor https://s01.oss.sonatype.org/#nexus-search;quick~vault-java-driver.

**Comment by henryx** [comment]
I know the problem, and I'm going to investigate how to solve asap. For now, you can use https://jitpack.io/ as falback repository. This issue remains open until I solve the problem definitivley

**Comment by brycechesternewman** [comment]
Unfortunately I can't use https://jitpack.io/  - it is blocked by our IT.

**Comment by brycechesternewman** [comment]
@henryx hello. Is there anything I can do to help get this working for 5.4.0 or are you planning on revisioning to 5.4.1 to fix this?

**Comment by henryx** [comment]
Finally, I've released this release to Maven Central, this issue can be closed
