### ISSUE TITLE
[BUG] TLS Version is set as minimum supported to JVM

### ISSUE THREAD

**Issue by Harishdr27** [jopenlibs/vault-java-driver#45]
**Describe the bug**
security scan complains about implementation of TLS.  
SSLContext.getInstance("TLS")  

rest/Rest.java 79
SslConfig.java 581
SslConfig.java 646

This can be change changed to a newer version of TLS as an example to resolve the vulnerability 

from 
SSLContext.getInstance("TLS")  
to
SSLContext.getInstance("TLSv1.2").

**To Reproduce**

**Comment by henryx** [comment]
Thank you for reporting, I've set minimum TLS version as 1.2
