### ISSUE TITLE
[BUG] Connections to a vault server on localhost fails

### ISSUE THREAD

**Issue by HomeOfTheWizard** [jopenlibs/vault-java-driver#48]
Hi,

I am trying to use your library instead of the non maintained version of bettercloud.
I am also trying to maintain a non continuing maven plugin.
https://github.com/HomeOfTheWizard/vault-maven-plugin/issues/2

I tried the latest release version of 6.0.0, but the integration tests that were passing with bettercloud, fails.
Environment:
JDK 11
Windows 
Vault latest (1.14)

Then checked out the version from master 7.6.1 and it worked. Apparently the bug is already fixed.
Do you have an approximative release date ?

Thanks and regards 🖖

**Comment by henryx** [comment]
Hi, today I've released new version

**Comment by HomeOfTheWizard** [comment]
Hi Henry, thanks for the quick reply.
Unfortunately I have the same issue with the 6.1.0.
I will try to see what is the root cause and the fix on 7.6.1.

**Comment by HomeOfTheWizard** [comment]
Alright, sorry for the false alert.
It was my https certificate that was not matching my local dns mapped hostname.
All good! I will release my next version using your library instead of betterCloud's.
https://github.com/HomeOfTheWizard/vault-maven-plugin/pull/8
