### ISSUE TITLE
[TASK] Integration tests refactoring

### ISSUE THREAD

**Issue by tledkov** [jopenlibs/vault-java-driver#8]
Use parametrized tests to check different versions of the vault. Now tests for the latest version of vault are copy-pasted.

**Comment by henryx** [comment]
Simple method to made this task is to introduce an environment variable and populate it via github actions with the version of Vault which we test. Only issue to this is we need to exclude tests that are obsoleted from one version to another (see for example AppID method, which is declared obsolete from Vault 0.6.1 and from Vault 1.11.7 stops working). See the PR for the implementation
